version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_php_fpm
        container_name: app
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        ports:
            - "8087:80"
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        container_name: mysql
        restart: always
        image: mysql:latest
        platform: linux/x86_64
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./db-data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    dbdata:
