version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_php_fpm
        container_name: book-library-app
        restart: always
        volumes:
            - .:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel

    web:
        image: nginx:alpine
        container_name: laravel_nginx
        restart: always
        volumes:
            - .:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        ports:
            - "8087:80"
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0.4
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: booklibrary
            MYSQL_USER: appclient
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
